add nvm support
divio/djangocms-boilerplate-webpack pull request #9
Opened 2017-03-02 11:43 UTC by Chive

2017-03-02 12:58 UTC, FinalAngel commented
nice 👍

2017-03-12 11:21 UTC, vxsx approved these changes
oink

2017-03-15 08:09 UTC, FinalAngel requested changes
@Chive please add the scripts to ``/tools/docker/``

2017-03-15 08:46 UTC, FinalAngel approved these changes

2017-03-15 18:32 UTC, merged